-- =====================================================================
-- 002 — Mapa: ubicaciones, radioenlaces e historial de ubicación de activos
-- =====================================================================
--
-- Qué agrega
--   tipos_ubicacion      Catálogo configurable (torre, oficina, bodega, …).
--                        Mismo patrón que estado_opciones: clave "valor"
--                        inmutable, "activo" para retirar sin borrar.
--   ubicaciones          Cualquier lugar con coordenadas. Una torre es una
--                        ubicación de tipo 'torre' (así una azotea con radio
--                        no tiene que existir dos veces).
--   equipos_radioenlace  Radios instalados en una ubicación. "activo_id" es
--                        opcional (un radio del proveedor no es un activo
--                        nuestro) y único: un activo no puede ser dos equipos.
--   enlaces              Pares de equipos con línea de vista. Un enlace es
--                        simétrico: A↔B se guarda una sola vez (índice único
--                        sobre LEAST/GREATEST) y un equipo puede tener varios
--                        enlaces (sirve para PtP y PtMP).
--   historial_ubicacion  Tramos desde/hasta por activo, como historial_custodia.
--                        Mover un activo = un solo INSERT: el trigger cierra el
--                        tramo vigente con la fecha del nuevo.
--
-- Decisiones que conviene no "arreglar" sin leer esto
--   * Las FK hacia activos(id) son ON DELETE CASCADE / SET NULL, nunca
--     RESTRICT: f_dar_baja() BORRA la fila de activos (el snapshot va a
--     bajas.activo), así que un RESTRICT rompería "Dar de baja".
--   * f_dar_baja/f_restaurar_baja se reemplazan con la MISMA firma (sin
--     sobrecargas nuevas en pg_proc) solo para guardar y restaurar el
--     historial de ubicación en el snapshot, igual que ya hacen con el de
--     custodia. Al restaurar, el activo recibe un id nuevo (comportamiento
--     previo de f_restaurar_baja) y sus tramos se reinsertan con ese id;
--     los de una ubicación que ya no exista se omiten para no bloquear la
--     restauración.
--   * Un activo vinculado a un equipo de radioenlace se ubica a través del
--     equipo: el trigger de equipos lo mueve solo, y los triggers de
--     historial_ubicacion impiden moverlo o sacarlo "por fuera".
--   * Escritura: ubicaciones/equipos/enlaces/tipos solo administrador
--     (es_admin(), como tipos_activo). historial_ubicacion usa la acción
--     nueva 'asignar_ubicacion' de la matriz (puede()), más
--     'restaurar_baja' para que f_restaurar_baja pueda reinsertar tramos,
--     igual que ins_historial en historial_custodia.
--   * Lectura: a diferencia de tipos_activo (SELECT abierto), ubicaciones,
--     equipos e historial exigen puede('ver_listado') o puede('ver_mapa'),
--     y enlaces puede('ver_mapa'): son la topología de la red y no deben
--     quedar legibles con la clave publicable (rol anon).
--   * GRANT explícito a anon/authenticated: el ACL por defecto de postgres
--     en public solo da Dxtm a esos roles, por eso una tabla creada desde el
--     SQL Editor responde "permission denied" sin él. Las columnas id son
--     IDENTITY, que no necesita GRANT sobre la secuencia.
--   * Fechas "de hoy" en el servidor: (now() AT TIME ZONE 'America/Guayaquil')::date,
--     no current_date (la base corre en UTC y después de las 19:00 en
--     Ecuador current_date ya es mañana).
--
-- Cómo correrla: pegar TODO el archivo en el SQL Editor de Supabase y
-- ejecutar. Va en una sola transacción: si algo falla, no queda nada a medias.
-- =====================================================================

BEGIN;

DO $$
BEGIN
  IF to_regclass('public.ubicaciones') IS NOT NULL THEN
    RAISE EXCEPTION 'La migración 002 ya fue aplicada (public.ubicaciones existe).';
  END IF;
END $$;

-- ---------------------------------------------------------------------
-- 1. Tablas
-- ---------------------------------------------------------------------

CREATE TABLE public.tipos_ubicacion (
  valor      text PRIMARY KEY,
  etiqueta   text NOT NULL,
  color      text NOT NULL DEFAULT '#57697C',
  orden      integer NOT NULL DEFAULT 0,
  activo     boolean NOT NULL DEFAULT true,
  creado_en  timestamptz NOT NULL DEFAULT now(),
  creado_por uuid DEFAULT auth.uid()
);
COMMENT ON TABLE public.tipos_ubicacion IS 'Catálogo configurable de tipos de ubicación (mapa). Clave valor inmutable; activo=false para retirar.';

INSERT INTO public.tipos_ubicacion (valor, etiqueta, color, orden) VALUES
  ('torre',   'Torre',   '#EC741D', 10),
  ('oficina', 'Oficina', '#004DAB', 20),
  ('bodega',  'Bodega',  '#A6710B', 30),
  ('otro',    'Otro',    '#57697C', 40);

CREATE TABLE public.ubicaciones (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre     text NOT NULL CONSTRAINT ubicaciones_nombre_no_vacio CHECK (btrim(nombre) <> ''),
  tipo       text NOT NULL REFERENCES public.tipos_ubicacion(valor) ON UPDATE CASCADE,
  lat        double precision NOT NULL CONSTRAINT ubicaciones_lat_rango CHECK (lat BETWEEN -90 AND 90),
  lng        double precision NOT NULL CONSTRAINT ubicaciones_lng_rango CHECK (lng BETWEEN -180 AND 180),
  direccion  text,
  notas      text,
  fotos      text[] NOT NULL DEFAULT '{}',
  activa     boolean NOT NULL DEFAULT true,
  creado_en  timestamptz NOT NULL DEFAULT now(),
  creado_por uuid DEFAULT auth.uid()
);
COMMENT ON TABLE public.ubicaciones IS 'Lugares con coordenadas (torres, oficinas, bodegas…). activa=false archiva sin perder el historial que la referencia.';
COMMENT ON COLUMN public.ubicaciones.fotos IS 'Rutas en el bucket fotos-activos, bajo ubicaciones/<id>/ (mismo formato que activos.fotos).';
-- Nombre único sin importar mayúsculas ni espacios de más (el caso
-- "Fuente de Alimentación" / "Fuente de alimentación" no se repite aquí).
CREATE UNIQUE INDEX ubicaciones_nombre_unico ON public.ubicaciones (lower(btrim(nombre)));
CREATE INDEX ubicaciones_tipo_idx ON public.ubicaciones (tipo);

CREATE TABLE public.equipos_radioenlace (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ubicacion_id bigint NOT NULL REFERENCES public.ubicaciones(id) ON DELETE RESTRICT,
  nombre       text NOT NULL CONSTRAINT equipos_radioenlace_nombre_no_vacio CHECK (btrim(nombre) <> ''),
  modelo       text,
  activo_id    integer REFERENCES public.activos(id) ON DELETE SET NULL,
  notas        text,
  creado_en    timestamptz NOT NULL DEFAULT now(),
  creado_por   uuid DEFAULT auth.uid(),
  CONSTRAINT equipos_radioenlace_activo_unico UNIQUE (activo_id)
);
COMMENT ON TABLE public.equipos_radioenlace IS 'Equipos de radioenlace instalados en una ubicación. activo_id opcional y único; al vincularlo, el activo pasa solo a esta ubicación.';
-- También sirve de índice para buscar equipos por ubicación (columna líder).
CREATE UNIQUE INDEX equipos_radioenlace_nombre_unico ON public.equipos_radioenlace (ubicacion_id, lower(btrim(nombre)));

CREATE TABLE public.enlaces (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipo_origen_id  bigint NOT NULL REFERENCES public.equipos_radioenlace(id) ON DELETE CASCADE,
  equipo_destino_id bigint NOT NULL REFERENCES public.equipos_radioenlace(id) ON DELETE CASCADE,
  banda             text,
  frecuencia_mhz    numeric(9,3) CONSTRAINT enlaces_frecuencia_positiva CHECK (frecuencia_mhz IS NULL OR frecuencia_mhz > 0),
  notas             text,
  creado_en         timestamptz NOT NULL DEFAULT now(),
  creado_por        uuid DEFAULT auth.uid(),
  CONSTRAINT enlaces_extremos_distintos CHECK (equipo_origen_id <> equipo_destino_id)
);
COMMENT ON TABLE public.enlaces IS 'Enlaces (línea de vista) entre dos equipos de ubicaciones distintas. Simétrico: A↔B se guarda una sola vez.';
CREATE UNIQUE INDEX enlaces_par_unico ON public.enlaces (LEAST(equipo_origen_id, equipo_destino_id), GREATEST(equipo_origen_id, equipo_destino_id));
CREATE INDEX enlaces_origen_idx ON public.enlaces (equipo_origen_id);
CREATE INDEX enlaces_destino_idx ON public.enlaces (equipo_destino_id);

CREATE TABLE public.historial_ubicacion (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activo_id      integer NOT NULL REFERENCES public.activos(id) ON DELETE CASCADE,
  ubicacion_id   bigint NOT NULL REFERENCES public.ubicaciones(id) ON DELETE RESTRICT,
  desde          date NOT NULL DEFAULT ((now() AT TIME ZONE 'America/Guayaquil')::date),
  hasta          date,
  notas          text,
  registrado_por uuid DEFAULT auth.uid(),
  creado_en      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT historial_ubicacion_fechas CHECK (hasta IS NULL OR hasta >= desde)
);
COMMENT ON TABLE public.historial_ubicacion IS 'Tramos de ubicación por activo (hasta NULL = vigente). Insertar un tramo vigente cierra el anterior (trigger).';
CREATE UNIQUE INDEX historial_ubicacion_un_vigente ON public.historial_ubicacion (activo_id) WHERE hasta IS NULL;
CREATE INDEX historial_ubicacion_activo_idx ON public.historial_ubicacion (activo_id, desde);
CREATE INDEX historial_ubicacion_ubicacion_idx ON public.historial_ubicacion (ubicacion_id);

-- ---------------------------------------------------------------------
-- 2. Reglas de negocio (triggers)
--    SECURITY DEFINER para que sus lecturas internas no dependan de la RLS
--    de quien ejecuta: la sentencia original ya pasó por la RLS; el trigger
--    solo aplica sus propias reglas.
-- ---------------------------------------------------------------------

-- 2a. Un enlace une equipos de ubicaciones distintas.
CREATE FUNCTION public.f_enlaces_validar()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE
  v_u_origen  bigint;
  v_u_destino bigint;
BEGIN
  SELECT ubicacion_id INTO v_u_origen  FROM public.equipos_radioenlace WHERE id = NEW.equipo_origen_id;
  SELECT ubicacion_id INTO v_u_destino FROM public.equipos_radioenlace WHERE id = NEW.equipo_destino_id;
  IF v_u_origen = v_u_destino THEN
    RAISE EXCEPTION 'Un enlace debe unir equipos de ubicaciones distintas.' USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER trg_enlaces_validar
  BEFORE INSERT OR UPDATE OF equipo_origen_id, equipo_destino_id ON public.enlaces
  FOR EACH ROW EXECUTE FUNCTION public.f_enlaces_validar();

-- 2b. Un equipo no puede mudarse a la ubicación del otro extremo de uno de sus enlaces.
CREATE FUNCTION public.f_equipos_radioenlace_validar()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
BEGIN
  IF NEW.ubicacion_id IS DISTINCT FROM OLD.ubicacion_id AND EXISTS (
    SELECT 1
      FROM public.enlaces l
      JOIN public.equipos_radioenlace o
        ON o.id = CASE WHEN l.equipo_origen_id = NEW.id THEN l.equipo_destino_id ELSE l.equipo_origen_id END
     WHERE (l.equipo_origen_id = NEW.id OR l.equipo_destino_id = NEW.id)
       AND o.ubicacion_id = NEW.ubicacion_id
  ) THEN
    RAISE EXCEPTION 'El equipo quedaría en la misma ubicación que el otro extremo de uno de sus enlaces.' USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER trg_equipos_radioenlace_validar
  BEFORE UPDATE OF ubicacion_id ON public.equipos_radioenlace
  FOR EACH ROW EXECUTE FUNCTION public.f_equipos_radioenlace_validar();

-- 2c. El activo vinculado a un equipo queda ubicado donde está el equipo
--     (abre un tramo nuevo; el trigger 2d cierra el anterior).
CREATE FUNCTION public.f_equipos_radioenlace_sincronizar_activo()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
BEGIN
  IF NEW.activo_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.historial_ubicacion
     WHERE activo_id = NEW.activo_id AND hasta IS NULL AND ubicacion_id = NEW.ubicacion_id
  ) THEN
    INSERT INTO public.historial_ubicacion (activo_id, ubicacion_id, desde, notas)
    VALUES (NEW.activo_id, NEW.ubicacion_id, (now() AT TIME ZONE 'America/Guayaquil')::date,
            'Automático: instalado como equipo de radioenlace «' || NEW.nombre || '»');
  END IF;
  RETURN NULL;
END $$;

CREATE TRIGGER trg_equipos_radioenlace_sincronizar_activo
  AFTER INSERT OR UPDATE OF activo_id, ubicacion_id ON public.equipos_radioenlace
  FOR EACH ROW EXECUTE FUNCTION public.f_equipos_radioenlace_sincronizar_activo();

-- 2d. Abrir un tramo vigente cierra el anterior (con la fecha del nuevo).
CREATE FUNCTION public.f_historial_ubicacion_antes_insertar()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE
  v_vigente record;
  v_equipo  record;
BEGIN
  -- Un tramo ya cerrado (carga histórica, o f_restaurar_baja) no toca el vigente.
  IF NEW.hasta IS NOT NULL THEN
    RETURN NEW;
  END IF;

  SELECT e.nombre AS equipo, u.nombre AS ubicacion INTO v_equipo
    FROM public.equipos_radioenlace e
    JOIN public.ubicaciones u ON u.id = e.ubicacion_id
   WHERE e.activo_id = NEW.activo_id AND e.ubicacion_id <> NEW.ubicacion_id;
  IF FOUND THEN
    RAISE EXCEPTION 'Este activo está instalado como equipo de radioenlace «%» en «%»: muévelo editando ese equipo.',
      v_equipo.equipo, v_equipo.ubicacion USING ERRCODE = '23514';
  END IF;

  SELECT id, ubicacion_id, desde INTO v_vigente
    FROM public.historial_ubicacion
   WHERE activo_id = NEW.activo_id AND hasta IS NULL
   FOR UPDATE;
  IF FOUND THEN
    IF v_vigente.ubicacion_id = NEW.ubicacion_id THEN
      RAISE EXCEPTION 'El activo ya está en esa ubicación.' USING ERRCODE = '23514';
    END IF;
    IF NEW.desde < v_vigente.desde THEN
      RAISE EXCEPTION 'La fecha del movimiento (%) es anterior a la llegada del activo a su ubicación actual (%).',
        to_char(NEW.desde, 'DD/MM/YYYY'), to_char(v_vigente.desde, 'DD/MM/YYYY') USING ERRCODE = '23514';
    END IF;
    UPDATE public.historial_ubicacion SET hasta = NEW.desde WHERE id = v_vigente.id;
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER trg_historial_ubicacion_antes_insertar
  BEFORE INSERT ON public.historial_ubicacion
  FOR EACH ROW EXECUTE FUNCTION public.f_historial_ubicacion_antes_insertar();

-- 2e. Reglas de edición de un tramo.
CREATE FUNCTION public.f_historial_ubicacion_antes_actualizar()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE
  v_equipo text;
BEGIN
  IF NEW.activo_id <> OLD.activo_id THEN
    RAISE EXCEPTION 'No se puede cambiar el activo de un tramo de ubicación.' USING ERRCODE = '23514';
  END IF;
  -- Corregir dónde o desde cuándo: solo administrador. auth.uid() NULL = sesión
  -- directa a la base (SQL Editor / service role), que no pasa por la RLS de la API.
  IF (NEW.ubicacion_id <> OLD.ubicacion_id OR NEW.desde <> OLD.desde)
     AND auth.uid() IS NOT NULL AND NOT coalesce(public.es_admin(), false) THEN
    RAISE EXCEPTION 'Solo un administrador puede corregir la ubicación o la fecha de inicio de un tramo.' USING ERRCODE = '42501';
  END IF;
  -- Sacar de su ubicación un activo que es equipo de radioenlace ahí: se hace desde el equipo.
  IF OLD.hasta IS NULL AND NEW.hasta IS NOT NULL THEN
    SELECT e.nombre INTO v_equipo
      FROM public.equipos_radioenlace e
     WHERE e.activo_id = OLD.activo_id AND e.ubicacion_id = OLD.ubicacion_id;
    IF FOUND THEN
      RAISE EXCEPTION 'Este activo está instalado como equipo de radioenlace «%»: desvincúlalo o mueve el equipo antes de sacarlo de esta ubicación.',
        v_equipo USING ERRCODE = '23514';
    END IF;
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER trg_historial_ubicacion_antes_actualizar
  BEFORE UPDATE ON public.historial_ubicacion
  FOR EACH ROW EXECUTE FUNCTION public.f_historial_ubicacion_antes_actualizar();

-- 2f. Auditoría: el mismo trigger genérico que ya usan activos, historial_custodia y bajas.
--     (tipos_ubicacion no lleva, igual que tipos_activo: su clave no es "id".)
CREATE TRIGGER audit_ubicaciones         AFTER INSERT OR DELETE OR UPDATE ON public.ubicaciones         FOR EACH ROW EXECUTE FUNCTION public.registrar_auditoria();
CREATE TRIGGER audit_equipos_radioenlace AFTER INSERT OR DELETE OR UPDATE ON public.equipos_radioenlace FOR EACH ROW EXECUTE FUNCTION public.registrar_auditoria();
CREATE TRIGGER audit_enlaces             AFTER INSERT OR DELETE OR UPDATE ON public.enlaces             FOR EACH ROW EXECUTE FUNCTION public.registrar_auditoria();
CREATE TRIGGER audit_historial_ubicacion AFTER INSERT OR DELETE OR UPDATE ON public.historial_ubicacion FOR EACH ROW EXECUTE FUNCTION public.registrar_auditoria();

-- ---------------------------------------------------------------------
-- 3. RLS (mismo estilo de nombres que el resto: sel_/ins_/upd_/del_<tabla>)
-- ---------------------------------------------------------------------

ALTER TABLE public.tipos_ubicacion     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ubicaciones         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.equipos_radioenlace ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enlaces             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.historial_ubicacion ENABLE ROW LEVEL SECURITY;

-- tipos_ubicacion: idéntico a tipos_activo / propiedad_opciones / estado_opciones.
CREATE POLICY sel_tipos_ubicacion ON public.tipos_ubicacion FOR SELECT USING (true);
CREATE POLICY ins_tipos_ubicacion ON public.tipos_ubicacion FOR INSERT WITH CHECK (public.es_admin());
CREATE POLICY upd_tipos_ubicacion ON public.tipos_ubicacion FOR UPDATE USING (public.es_admin());
CREATE POLICY del_tipos_ubicacion ON public.tipos_ubicacion FOR DELETE USING (public.es_admin());

-- ubicaciones / equipos_radioenlace: escribe solo admin; lee quien ve el listado o el mapa.
CREATE POLICY sel_ubicaciones ON public.ubicaciones FOR SELECT USING (public.puede('ver_listado') OR public.puede('ver_mapa'));
CREATE POLICY ins_ubicaciones ON public.ubicaciones FOR INSERT WITH CHECK (public.es_admin());
CREATE POLICY upd_ubicaciones ON public.ubicaciones FOR UPDATE USING (public.es_admin());
CREATE POLICY del_ubicaciones ON public.ubicaciones FOR DELETE USING (public.es_admin());

CREATE POLICY sel_equipos_radioenlace ON public.equipos_radioenlace FOR SELECT USING (public.puede('ver_listado') OR public.puede('ver_mapa'));
CREATE POLICY ins_equipos_radioenlace ON public.equipos_radioenlace FOR INSERT WITH CHECK (public.es_admin());
CREATE POLICY upd_equipos_radioenlace ON public.equipos_radioenlace FOR UPDATE USING (public.es_admin());
CREATE POLICY del_equipos_radioenlace ON public.equipos_radioenlace FOR DELETE USING (public.es_admin());

-- enlaces: la topología solo la ve quien ve el mapa.
CREATE POLICY sel_enlaces ON public.enlaces FOR SELECT USING (public.puede('ver_mapa'));
CREATE POLICY ins_enlaces ON public.enlaces FOR INSERT WITH CHECK (public.es_admin());
CREATE POLICY upd_enlaces ON public.enlaces FOR UPDATE USING (public.es_admin());
CREATE POLICY del_enlaces ON public.enlaces FOR DELETE USING (public.es_admin());

-- historial_ubicacion: asignar/mover con la acción de la matriz; corregir y borrar tramos cerrados, solo admin.
CREATE POLICY sel_historial_ubicacion ON public.historial_ubicacion FOR SELECT
  USING (public.puede('ver_listado') OR public.puede('ver_mapa'));
CREATE POLICY ins_historial_ubicacion ON public.historial_ubicacion FOR INSERT
  WITH CHECK (public.puede('asignar_ubicacion') OR public.puede('restaurar_baja'));
-- WITH CHECK explícito: sin él, PostgreSQL reevalúa el USING sobre la fila
-- nueva y cerrar un tramo (hasta pasa de NULL a una fecha) fallaría para
-- quien no es admin.
CREATE POLICY upd_historial_ubicacion ON public.historial_ubicacion FOR UPDATE
  USING ((hasta IS NULL AND public.puede('asignar_ubicacion')) OR public.es_admin())
  WITH CHECK (public.puede('asignar_ubicacion'));
CREATE POLICY del_historial_ubicacion ON public.historial_ubicacion FOR DELETE
  USING (public.es_admin() AND hasta IS NOT NULL);

-- ---------------------------------------------------------------------
-- 4. GRANT explícito (el SQL Editor no los aplica; ver encabezado)
-- ---------------------------------------------------------------------

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE
  public.tipos_ubicacion,
  public.ubicaciones,
  public.equipos_radioenlace,
  public.enlaces,
  public.historial_ubicacion
TO anon, authenticated;

-- ---------------------------------------------------------------------
-- 5. Baja / restauración: el snapshot también lleva el historial de ubicación.
--    MISMA firma que las versiones actuales (CREATE OR REPLACE conserva
--    dueño y permisos, y no crea sobrecargas). Los únicos cambios respecto a
--    la versión anterior están marcados con «002».
-- ---------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.f_dar_baja(p_activo_id integer, p_motivo text)
 RETURNS void
 LANGUAGE plpgsql
AS $function$ declare v_snapshot jsonb; begin select jsonb_build_object( 'id', a.id, 'propiedad', a.propiedad, 'tipo', a.tipo, 'marca', a.marca, 'modelo', a.modelo, 'serie', a.serie, 'nombre_dispositivo', a.nombre_dispositivo, 'mac_wifi', a.mac_wifi, 'mac_ethernet', a.mac_ethernet, 'sistema_operativo', a.sistema_operativo, 'ram_gb', a.ram_gb, 'disco_gb', a.disco_gb, 'procesador', a.procesador, 'proveedor', a.proveedor, 'fecha_adquisicion', a.fecha_adquisicion, 'celular_gmail', a.celular_gmail, 'celular_password', a.celular_password, 'trazabilidad', a.trazabilidad, 'estado', a.estado, 'valor_compra', a.valor_compra, 'vida_util_anios', a.vida_util_anios, 'color', a.color, 'longitud_m', a.longitud_m, 'fotos', a.fotos, 'historial_custodia', coalesce(( select jsonb_agg(jsonb_build_object('orden', h.orden, 'tipo_custodio', h.tipo_custodio, 'nombre', h.nombre, 'cargo', h.cargo, 'desde', h.desde, 'hasta', h.hasta, 'tipo_devolucion', h.tipo_devolucion, 'tipo_entrega', h.tipo_entrega, 'observacion_entrega', h.observacion_entrega, 'observacion_devolucion', h.observacion_devolucion) order by h.orden) from public.historial_custodia h where h.activo_id = a.id), '[]'::jsonb)
  -- «002» historial de ubicación en el snapshot (con el nombre, por si la ubicación se borra después)
  , 'historial_ubicacion', coalesce(( select jsonb_agg(jsonb_build_object('ubicacion_id', hu.ubicacion_id, 'ubicacion', u.nombre, 'desde', hu.desde, 'hasta', hu.hasta, 'notas', hu.notas, 'registrado_por', hu.registrado_por) order by hu.desde, hu.id) from public.historial_ubicacion hu left join public.ubicaciones u on u.id = hu.ubicacion_id where hu.activo_id = a.id), '[]'::jsonb)
  ) into v_snapshot from public.activos a where a.id = p_activo_id; if v_snapshot is null then raise exception 'Activo % no encontrado', p_activo_id; end if; insert into public.bajas (activo, motivo, dado_de_baja_por) values (v_snapshot, p_motivo, auth.uid()); delete from public.activos where id = p_activo_id; end; $function$;

CREATE OR REPLACE FUNCTION public.f_restaurar_baja(p_baja_id bigint)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$ declare v_activo jsonb; v_nuevo_id integer; begin select activo into v_activo from public.bajas where id = p_baja_id; if v_activo is null then raise exception 'Baja % no encontrada', p_baja_id; end if; insert into public.activos (propiedad, tipo, marca, modelo, serie, nombre_dispositivo, mac_wifi, mac_ethernet, sistema_operativo, ram_gb, disco_gb, procesador, proveedor, fecha_adquisicion, celular_gmail, celular_password, trazabilidad, estado, valor_compra, vida_util_anios, color, longitud_m, fotos) values (case when v_activo->>'propiedad' = 'propio' then coalesce(v_activo->>'empresa', 'lukmar') else v_activo->>'propiedad' end, v_activo->>'tipo', v_activo->>'marca', v_activo->>'modelo', v_activo->>'serie', v_activo->>'nombre_dispositivo', v_activo->>'mac_wifi', v_activo->>'mac_ethernet', v_activo->>'sistema_operativo', (v_activo->>'ram_gb')::numeric, (v_activo->>'disco_gb')::numeric, v_activo->>'procesador', v_activo->>'proveedor', (v_activo->>'fecha_adquisicion')::date, v_activo->>'celular_gmail', v_activo->>'celular_password', coalesce(v_activo->'trazabilidad', 'null'::jsonb), coalesce(v_activo->>'estado', 'uso'), (v_activo->>'valor_compra')::numeric, (v_activo->>'vida_util_anios')::numeric, v_activo->>'color', (v_activo->>'longitud_m')::numeric, case when jsonb_typeof(v_activo->'fotos') = 'array' then (select array_agg(x) from jsonb_array_elements_text(v_activo->'fotos') x) else array[]::text[] end ) returning id into v_nuevo_id; insert into public.historial_custodia (activo_id, orden, tipo_custodio, nombre, cargo, desde, hasta, tipo_devolucion, tipo_entrega, observacion_entrega, observacion_devolucion) select v_nuevo_id, (t->>'orden')::int, t->>'tipo_custodio', t->>'nombre', t->>'cargo', (t->>'desde')::date, (t->>'hasta')::date, t->>'tipo_devolucion', t->>'tipo_entrega', t->>'observacion_entrega', coalesce(t->>'observacion_devolucion', t->>'observacion') from jsonb_array_elements(coalesce(v_activo->'historial_custodia', '[]'::jsonb)) as t;
  -- «002» reinsertar el historial de ubicación con el id nuevo (se omiten tramos de ubicaciones que ya no existen)
  insert into public.historial_ubicacion (activo_id, ubicacion_id, desde, hasta, notas, registrado_por) select v_nuevo_id, (t->>'ubicacion_id')::bigint, (t->>'desde')::date, (t->>'hasta')::date, t->>'notas', (t->>'registrado_por')::uuid from jsonb_array_elements(coalesce(v_activo->'historial_ubicacion', '[]'::jsonb)) as t where exists (select 1 from public.ubicaciones u where u.id = (t->>'ubicacion_id')::bigint);
  delete from public.bajas where id = p_baja_id; return v_nuevo_id; end; $function$;

COMMIT;
