-- =====================================================================
-- 006 — Mapa: capa "Plano" (plano de la camaronera sobre el satélite)
-- =====================================================================
--
-- Qué agrega
--   planos_mapa   El plano que muestra la capa "Plano": la imagen (se publica
--                 con la app, en assets/img/mapa/) y dónde va sobre el mapa,
--                 como las coordenadas [lat, lng] de tres esquinas de la
--                 imagen: no (arriba-izquierda), ne (arriba-derecha) y so
--                 (abajo-izquierda). Con tres puntos alcanza para cualquier
--                 posición, tamaño y giro.
--                 esquinas             lo que se muestra; lo cambia "Ajustar plano".
--                 esquinas_originales  el calce con el que se publicó el plano,
--                                      para "Calce original".
--                 Solo un plano activo a la vez (índice único parcial).
--
-- Permisos: lo lee quien tiene "ver_mapa" (como la red); lo escribe solo el
-- administrador. GRANT explícito, como en la 002/003. Los cambios quedan en
-- auditoría (registrar_auditoria()).
--
-- Si esta migración no se corre, la capa Plano funciona igual con el calce
-- que trae la app (nucleo/plano-mapa.js, PLANO_POR_DEFECTO); lo único que no
-- se puede es guardar un ajuste.
--
-- Cómo correrla: pegar TODO el archivo en el SQL Editor de Supabase y
-- ejecutar. Va en una sola transacción: si algo falla, no queda nada a medias.
-- =====================================================================

BEGIN;

DO $$
BEGIN
  IF to_regclass('public.ubicaciones') IS NULL THEN
    RAISE EXCEPTION 'Falta la migración 002 (public.ubicaciones no existe).';
  END IF;
  IF to_regclass('public.planos_mapa') IS NOT NULL THEN
    RAISE EXCEPTION 'La migración 006 ya fue aplicada (public.planos_mapa existe).';
  END IF;
  IF to_regprocedure('public.registrar_auditoria()') IS NULL OR to_regprocedure('public.puede(text)') IS NULL OR to_regprocedure('public.es_admin()') IS NULL THEN
    RAISE EXCEPTION 'Faltan funciones base (registrar_auditoria, puede, es_admin).';
  END IF;
END $$;

-- ---------------------------------------------------------------------
-- 1. Validación de las esquinas (la usa el CHECK). Mismas reglas que
--    esquinasValidas() en nucleo/plano-mapa.js.
-- ---------------------------------------------------------------------

CREATE FUNCTION public.f_planos_esquinas_validas(e jsonb)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
SET search_path = ''
AS $$
  SELECT CASE
    WHEN e IS NULL OR jsonb_typeof(e) <> 'object' THEN false
    WHEN NOT (SELECT bool_and(coalesce(
                jsonb_typeof(e -> k) = 'array'
                AND jsonb_array_length(e -> k) = 2
                AND jsonb_typeof(e -> k -> 0) = 'number'
                AND jsonb_typeof(e -> k -> 1) = 'number', false))
              FROM unnest(ARRAY['no', 'ne', 'so']) AS k) THEN false
    WHEN NOT (SELECT bool_and((e -> k ->> 0)::float8 BETWEEN -90 AND 90 AND (e -> k ->> 1)::float8 BETWEEN -180 AND 180)
              FROM unnest(ARRAY['no', 'ne', 'so']) AS k) THEN false
    ELSE abs(((e -> 'ne' ->> 1)::float8 - (e -> 'no' ->> 1)::float8) * ((e -> 'so' ->> 0)::float8 - (e -> 'no' ->> 0)::float8)
           - ((e -> 'ne' ->> 0)::float8 - (e -> 'no' ->> 0)::float8) * ((e -> 'so' ->> 1)::float8 - (e -> 'no' ->> 1)::float8)) > 1e-12
  END
$$;
COMMENT ON FUNCTION public.f_planos_esquinas_validas(jsonb) IS 'true si e = {"no":[lat,lng],"ne":[lat,lng],"so":[lat,lng]} con coordenadas en rango y las tres esquinas no alineadas.';

-- ---------------------------------------------------------------------
-- 2. Tabla
-- ---------------------------------------------------------------------

CREATE TABLE public.planos_mapa (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre              text NOT NULL CONSTRAINT planos_mapa_nombre_no_vacio CHECK (btrim(nombre) <> ''),
  imagen              text NOT NULL CONSTRAINT planos_mapa_imagen_de_la_app CHECK (imagen ~ '^assets/[A-Za-z0-9._/-]+\.(webp|png|jpg|jpeg)$' AND imagen !~ '\.\.'),
  ancho_px            integer NOT NULL CONSTRAINT planos_mapa_ancho_positivo CHECK (ancho_px > 0),
  alto_px             integer NOT NULL CONSTRAINT planos_mapa_alto_positivo CHECK (alto_px > 0),
  esquinas            jsonb NOT NULL CONSTRAINT planos_mapa_esquinas_validas CHECK (public.f_planos_esquinas_validas(esquinas)),
  esquinas_originales jsonb NOT NULL CONSTRAINT planos_mapa_originales_validas CHECK (public.f_planos_esquinas_validas(esquinas_originales)),
  activo              boolean NOT NULL DEFAULT true,
  actualizado_en      timestamptz NOT NULL DEFAULT now(),
  actualizado_por     uuid DEFAULT auth.uid()
);
COMMENT ON TABLE public.planos_mapa IS 'Plano de la capa "Plano" del mapa: imagen de la app y sus tres esquinas sobre el mapa. Un solo plano activo.';
COMMENT ON COLUMN public.planos_mapa.esquinas IS '{"no":[lat,lng],"ne":[lat,lng],"so":[lat,lng]}: arriba-izquierda, arriba-derecha y abajo-izquierda de la imagen. Lo cambia "Ajustar plano".';
COMMENT ON COLUMN public.planos_mapa.esquinas_originales IS 'Calce con el que se publicó el plano ("Calce original" en Ajustar plano).';
CREATE UNIQUE INDEX planos_mapa_un_activo ON public.planos_mapa ((true)) WHERE activo;

-- Quién y cuándo tocó el ajuste por última vez.
CREATE FUNCTION public.f_planos_mapa_actualizado()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  NEW.actualizado_en := now();
  NEW.actualizado_por := auth.uid();
  RETURN NEW;
END $$;
CREATE TRIGGER trg_planos_mapa_actualizado BEFORE UPDATE ON public.planos_mapa FOR EACH ROW EXECUTE FUNCTION public.f_planos_mapa_actualizado();
CREATE TRIGGER audit_planos_mapa AFTER INSERT OR DELETE OR UPDATE ON public.planos_mapa FOR EACH ROW EXECUTE FUNCTION public.registrar_auditoria();

-- ---------------------------------------------------------------------
-- 3. RLS (sel_/ins_/upd_/del_<tabla>, como el resto)
-- ---------------------------------------------------------------------

ALTER TABLE public.planos_mapa ENABLE ROW LEVEL SECURITY;
CREATE POLICY sel_planos_mapa ON public.planos_mapa FOR SELECT USING (public.puede('ver_mapa'));
CREATE POLICY ins_planos_mapa ON public.planos_mapa FOR INSERT WITH CHECK (public.es_admin());
CREATE POLICY upd_planos_mapa ON public.planos_mapa FOR UPDATE USING (public.es_admin()) WITH CHECK (public.es_admin());
CREATE POLICY del_planos_mapa ON public.planos_mapa FOR DELETE USING (public.es_admin());

-- ---------------------------------------------------------------------
-- 4. GRANT explícito (ver el encabezado de la 002). id es IDENTITY: no
--    hace falta GRANT sobre la secuencia.
-- ---------------------------------------------------------------------

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.planos_mapa TO anon, authenticated;
REVOKE ALL ON FUNCTION public.f_planos_esquinas_validas(jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.f_planos_esquinas_validas(jsonb) TO anon, authenticated;

-- ---------------------------------------------------------------------
-- 5. El plano que trae la app (mismo calce que PLANO_POR_DEFECTO)
-- ---------------------------------------------------------------------

INSERT INTO public.planos_mapa (nombre, imagen, ancho_px, alto_px, esquinas, esquinas_originales)
VALUES (
  'Camaronera Lukmar — plano general (lotes actualizados, agosto 2026)',
  'assets/img/mapa/plano-lukmar-2026-08.webp',
  3198, 4018,
  '{"no": [-2.3111634, -79.738091], "ne": [-2.3110121, -79.700257], "so": [-2.3589797, -79.7379023]}',
  '{"no": [-2.3111634, -79.738091], "ne": [-2.3110121, -79.700257], "so": [-2.3589797, -79.7379023]}'
);

COMMIT;
