-- =====================================================================
-- 007 — Red de la finca: tipos de equipo, redes y atajos de simulación
-- =====================================================================
--
-- Qué agrega
--   tipos_equipo_red   Catálogo de tipos de equipo de red (Router, Switch,
--                      Punto a Punto, AP, Estación, Cámara, NVR…). Con el
--                      tipo, la app arma sola el nombre de cada equipo:
--                      "Estación en Torre K enlazada a Punto a Punto en Torre L"
--                      (el género concuerda: enlazada/enlazado, conectada/…).
--   redes              Las redes de la finca (la persona trabaja con tres).
--                      Las crea y nombra el administrador.
--   equipos_radioenlace  + tipo_equipo, red_id y referencia (texto corto
--                      opcional que distingue equipos iguales, p. ej. "Norte").
--                      "nombre" sigue existiendo: la app lo llena con el
--                      nombre automático al guardar.
--   atajos_simulacion  Atajos con nombre para simular la caída de uno o más
--                      equipos con un toggle ("Red 2", "PtP Torre K"…). La
--                      simulación sigue sin guardarse: el atajo solo recuerda
--                      QUÉ equipos apagar.
--
-- Permisos: se leen con "ver_mapa" (como la red, ver la 004); se escriben solo
-- con el administrador. GRANT explícito, como en la 002/003/006. Auditoría en
-- redes y atajos (el catálogo de tipos, como tipos_ubicacion, no tiene id y
-- no pasa por registrar_auditoria()).
--
-- Si esta migración no se corre, la app sigue como antes: el nombre del
-- equipo se escribe a mano y no aparecen tipo, red ni atajos.
--
-- Cómo correrla: pegar TODO el archivo en el SQL Editor de Supabase y
-- ejecutar. Va en una sola transacción: si algo falla, no queda nada a medias.
-- =====================================================================

BEGIN;

DO $$
BEGIN
  IF to_regclass('public.equipos_radioenlace') IS NULL THEN
    RAISE EXCEPTION 'Falta la migración 002 (public.equipos_radioenlace no existe).';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'equipos_radioenlace' AND column_name = 'servidor_id') THEN
    RAISE EXCEPTION 'Falta la migración 003 (equipos_radioenlace.servidor_id no existe).';
  END IF;
  IF to_regclass('public.tipos_equipo_red') IS NOT NULL THEN
    RAISE EXCEPTION 'La migración 007 ya fue aplicada (public.tipos_equipo_red existe).';
  END IF;
  IF to_regprocedure('public.registrar_auditoria()') IS NULL OR to_regprocedure('public.puede(text)') IS NULL OR to_regprocedure('public.es_admin()') IS NULL THEN
    RAISE EXCEPTION 'Faltan funciones base (registrar_auditoria, puede, es_admin).';
  END IF;
END $$;

-- ---------------------------------------------------------------------
-- 1. Tipos de equipo de red
-- ---------------------------------------------------------------------

CREATE TABLE public.tipos_equipo_red (
  valor      text PRIMARY KEY CONSTRAINT tipos_equipo_red_valor_formato CHECK (valor ~ '^[a-z0-9_]{1,40}$'),
  etiqueta   text NOT NULL CONSTRAINT tipos_equipo_red_etiqueta_valida CHECK (btrim(etiqueta) <> '' AND char_length(etiqueta) <= 40),
  genero     text NOT NULL DEFAULT 'm' CONSTRAINT tipos_equipo_red_genero_valido CHECK (genero IN ('m', 'f')),
  orden      integer NOT NULL DEFAULT 0,
  activo     boolean NOT NULL DEFAULT true,
  creado_en  timestamptz NOT NULL DEFAULT now(),
  creado_por uuid DEFAULT auth.uid()
);
COMMENT ON TABLE public.tipos_equipo_red IS 'Tipos de equipo de red. La etiqueta arma el nombre automático del equipo; genero (m/f) hace concordar "enlazado/enlazada".';
CREATE UNIQUE INDEX tipos_equipo_red_etiqueta_unica ON public.tipos_equipo_red (lower(btrim(etiqueta)));

INSERT INTO public.tipos_equipo_red (valor, etiqueta, genero, orden) VALUES
  ('router',   'Router',        'm', 10),
  ('switch',   'Switch',        'm', 20),
  ('ptp',      'Punto a Punto', 'm', 30),
  ('ap',       'AP',            'm', 40),
  ('estacion', 'Estación',      'f', 50),
  ('camara',   'Cámara',        'f', 60),
  ('nvr',      'NVR',           'm', 70),
  ('otro',     'Equipo',        'm', 90);

-- ---------------------------------------------------------------------
-- 2. Redes de la finca
-- ---------------------------------------------------------------------

CREATE TABLE public.redes (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre     text NOT NULL CONSTRAINT redes_nombre_valido CHECK (btrim(nombre) <> '' AND char_length(nombre) <= 60),
  color      text NOT NULL DEFAULT '#007EB2' CONSTRAINT redes_color_valido CHECK (color ~ '^#[0-9A-Fa-f]{6}$'),
  orden      integer NOT NULL DEFAULT 0,
  activa     boolean NOT NULL DEFAULT true,
  creado_en  timestamptz NOT NULL DEFAULT now(),
  creado_por uuid DEFAULT auth.uid()
);
COMMENT ON TABLE public.redes IS 'Redes de la finca (p. ej. las tres de Lukmar). Cada equipo de red pertenece a una (red_id).';
CREATE UNIQUE INDEX redes_nombre_unico ON public.redes (lower(btrim(nombre)));

-- ---------------------------------------------------------------------
-- 3. Equipos: tipo, red y referencia
-- ---------------------------------------------------------------------

ALTER TABLE public.equipos_radioenlace
  ADD COLUMN tipo_equipo text CONSTRAINT equipos_radioenlace_tipo_fk REFERENCES public.tipos_equipo_red(valor) ON UPDATE CASCADE,
  ADD COLUMN red_id      bigint CONSTRAINT equipos_radioenlace_red_fk REFERENCES public.redes(id) ON DELETE SET NULL,
  ADD COLUMN referencia  text CONSTRAINT equipos_radioenlace_referencia_valida CHECK (referencia IS NULL OR (btrim(referencia) <> '' AND char_length(referencia) <= 60));
COMMENT ON COLUMN public.equipos_radioenlace.tipo_equipo IS 'Tipo de equipo (tipos_equipo_red). Con él la app arma el nombre automático.';
COMMENT ON COLUMN public.equipos_radioenlace.red_id IS 'Red de la finca a la que pertenece (redes). Al borrar la red queda en NULL.';
COMMENT ON COLUMN public.equipos_radioenlace.referencia IS 'Texto corto opcional que distingue equipos iguales en el nombre automático (p. ej. "Norte").';
CREATE INDEX equipos_radioenlace_red_idx ON public.equipos_radioenlace (red_id);
CREATE INDEX equipos_radioenlace_tipo_idx ON public.equipos_radioenlace (tipo_equipo);

-- ---------------------------------------------------------------------
-- 4. Atajos de simulación
-- ---------------------------------------------------------------------

CREATE TABLE public.atajos_simulacion (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre     text NOT NULL CONSTRAINT atajos_simulacion_nombre_valido CHECK (btrim(nombre) <> '' AND char_length(nombre) <= 60),
  equipos    bigint[] NOT NULL CONSTRAINT atajos_simulacion_con_equipos CHECK (cardinality(equipos) BETWEEN 1 AND 200),
  orden      integer NOT NULL DEFAULT 0,
  creado_en  timestamptz NOT NULL DEFAULT now(),
  creado_por uuid DEFAULT auth.uid()
);
COMMENT ON TABLE public.atajos_simulacion IS 'Atajos con nombre para simular la caída de uno o más equipos (ids de equipos_radioenlace). La simulación no se guarda: esto solo recuerda qué equipos apagar.';
CREATE UNIQUE INDEX atajos_simulacion_nombre_unico ON public.atajos_simulacion (lower(btrim(nombre)));

-- Equipos que existen, sin NULL ni repetidos (se guardan ordenados).
CREATE FUNCTION public.f_atajos_simulacion_validar()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
DECLARE
  v_faltan bigint[];
BEGIN
  IF array_position(NEW.equipos, NULL) IS NOT NULL THEN
    RAISE EXCEPTION 'Un atajo no puede tener equipos vacíos.' USING ERRCODE = '23514', CONSTRAINT = 'atajos_simulacion_con_equipos';
  END IF;
  NEW.equipos := ARRAY(SELECT DISTINCT x FROM unnest(NEW.equipos) AS x ORDER BY x);
  SELECT array_agg(x ORDER BY x) INTO v_faltan
    FROM unnest(NEW.equipos) AS x
   WHERE NOT EXISTS (SELECT 1 FROM public.equipos_radioenlace e WHERE e.id = x);
  IF v_faltan IS NOT NULL THEN
    RAISE EXCEPTION 'El atajo apunta a equipos que no existen: %', v_faltan USING ERRCODE = '23503', CONSTRAINT = 'atajos_simulacion_equipos_existen';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_atajos_simulacion_validar BEFORE INSERT OR UPDATE ON public.atajos_simulacion FOR EACH ROW EXECUTE FUNCTION public.f_atajos_simulacion_validar();

-- Al borrar un equipo se lo saca de los atajos (y se borra el atajo que
-- quedaría vacío). SECURITY DEFINER: es mantenimiento de la base, no una
-- escritura de la persona.
CREATE FUNCTION public.f_atajos_quitar_equipo()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  DELETE FROM public.atajos_simulacion WHERE equipos = ARRAY[OLD.id]::bigint[];
  UPDATE public.atajos_simulacion SET equipos = array_remove(equipos, OLD.id) WHERE OLD.id = ANY (equipos);
  RETURN OLD;
END $$;
CREATE TRIGGER trg_equipos_radioenlace_quitar_de_atajos AFTER DELETE ON public.equipos_radioenlace FOR EACH ROW EXECUTE FUNCTION public.f_atajos_quitar_equipo();

CREATE TRIGGER audit_redes AFTER INSERT OR DELETE OR UPDATE ON public.redes FOR EACH ROW EXECUTE FUNCTION public.registrar_auditoria();
CREATE TRIGGER audit_atajos_simulacion AFTER INSERT OR DELETE OR UPDATE ON public.atajos_simulacion FOR EACH ROW EXECUTE FUNCTION public.registrar_auditoria();

-- ---------------------------------------------------------------------
-- 5. RLS (sel_/ins_/upd_/del_<tabla>, como el resto)
-- ---------------------------------------------------------------------

ALTER TABLE public.tipos_equipo_red ENABLE ROW LEVEL SECURITY;
CREATE POLICY sel_tipos_equipo_red ON public.tipos_equipo_red FOR SELECT USING (public.puede('ver_mapa'));
CREATE POLICY ins_tipos_equipo_red ON public.tipos_equipo_red FOR INSERT WITH CHECK (public.es_admin());
CREATE POLICY upd_tipos_equipo_red ON public.tipos_equipo_red FOR UPDATE USING (public.es_admin()) WITH CHECK (public.es_admin());
CREATE POLICY del_tipos_equipo_red ON public.tipos_equipo_red FOR DELETE USING (public.es_admin());

ALTER TABLE public.redes ENABLE ROW LEVEL SECURITY;
CREATE POLICY sel_redes ON public.redes FOR SELECT USING (public.puede('ver_mapa'));
CREATE POLICY ins_redes ON public.redes FOR INSERT WITH CHECK (public.es_admin());
CREATE POLICY upd_redes ON public.redes FOR UPDATE USING (public.es_admin()) WITH CHECK (public.es_admin());
CREATE POLICY del_redes ON public.redes FOR DELETE USING (public.es_admin());

ALTER TABLE public.atajos_simulacion ENABLE ROW LEVEL SECURITY;
CREATE POLICY sel_atajos_simulacion ON public.atajos_simulacion FOR SELECT USING (public.puede('ver_mapa'));
CREATE POLICY ins_atajos_simulacion ON public.atajos_simulacion FOR INSERT WITH CHECK (public.es_admin());
CREATE POLICY upd_atajos_simulacion ON public.atajos_simulacion FOR UPDATE USING (public.es_admin()) WITH CHECK (public.es_admin());
CREATE POLICY del_atajos_simulacion ON public.atajos_simulacion FOR DELETE USING (public.es_admin());

-- ---------------------------------------------------------------------
-- 6. GRANT explícito (ver el encabezado de la 002). Los id son IDENTITY: no
--    hace falta GRANT sobre secuencias. Las funciones de trigger no
--    necesitan EXECUTE para quien escribe.
-- ---------------------------------------------------------------------

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.tipos_equipo_red, public.redes, public.atajos_simulacion TO anon, authenticated;
REVOKE ALL ON FUNCTION public.f_atajos_simulacion_validar() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.f_atajos_quitar_equipo() FROM PUBLIC;

COMMIT;
