-- =====================================================================
-- 012 — Campos configurables de los activos (v10)
-- =====================================================================
--
-- Qué cambia
--   * campos_activo: las definiciones de los campos de los activos. Trae de
--     semilla los 9 de siempre («fijos»: son columnas de activos — serie,
--     sistema operativo, RAM, almacenamiento, procesador, las dos MAC, color
--     y longitud); el administrador agrega los suyos (IMEI, número de
--     línea…), con su tipo de dato: texto, texto largo, número (con unidad),
--     fecha, sí/no o lista de opciones. Un solo orden para todos los tipos.
--     A los fijos se les cambia la etiqueta, la unidad, el orden y las
--     reglas; no se borran, no se desactivan ni cambian de tipo de dato.
--   * activos.personalizados (jsonb): { <clave>: valor } de los campos
--     nuevos. Al guardar, la base mezcla lo que llega con lo que había
--     (OLD || NEW) y quita los null: así un campo que el tipo oculta no se
--     pierde y un campo vaciado se borra. Cada valor que cambia se valida
--     según su tipo de dato.
--   * tipos_activo.campos_obligatorios (jsonb): las claves obligatorias de
--     cada tipo (la app las exige en el formulario del activo).
--     campos_pertinentes sigue siendo la lista de claves que usa el tipo.
--   * «Único»: un campo marcado no puede repetir su valor entre activos
--     (sin distinguir mayúsculas ni espacios; los números, como números).
--     No se deja marcar si ya hay valores repetidos.
--   * «En el acta»: el campo sale en la descripción del ítem del acta.
--   * f_dar_baja / f_restaurar_baja: la copia lleva también personalizados.
--     MISMA firma (CREATE OR REPLACE conserva dueño y permisos); antes se
--     comprueba que sean las de la 002, para no pisar otra versión.
--   * renombrar_tipo_activo(viejo, nuevo): cambia el nombre de un tipo de
--     activo (la FK activos_tipo_fkey, con ON UPDATE CASCADE, lo lleva a los
--     activos) y también en las copias de las bajas, para que restaurarlas
--     no falle. Solo administradores; «Celular» no se renombra.
--   * tipos_ubicacion.icono_svg: el ícono de la burbuja en el mapa.
--
-- Sin esta migración la app (v10) funciona como el v9: se esconde lo que
-- falta. Y el v9 publicado sigue funcionando con ella aplicada.
--
-- Necesita la 011. Cómo correrla: pegar TODO el archivo en el SQL Editor de
-- Supabase y ejecutar. Va en una sola transacción: si algo falla, no queda
-- nada a medias. Si ya fue aplicada, se niega sin tocar nada.
-- =====================================================================

BEGIN;

DO $$
BEGIN
  IF to_regprocedure('public.f_red_efectiva(bigint)') IS NULL THEN
    RAISE EXCEPTION 'Falta la migración 011 (public.f_red_efectiva no existe).';
  END IF;
  IF to_regclass('public.campos_activo') IS NOT NULL THEN
    RAISE EXCEPTION 'La migración 012 ya fue aplicada (public.campos_activo existe).';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                  WHERE table_schema = 'public' AND table_name = 'tipos_activo' AND column_name = 'campos_pertinentes' AND udt_name = 'jsonb') THEN
    RAISE EXCEPTION 'tipos_activo.campos_pertinentes no es jsonb: revisa el esquema antes de aplicar la 012.';
  END IF;
  -- f_dar_baja y f_restaurar_baja se reemplazan: tienen que ser las de la 002.
  IF md5(pg_get_functiondef('public.f_dar_baja(integer, text)'::regprocedure)) <> '861f49998b15381a124a924d39dad8de'
     OR md5(pg_get_functiondef('public.f_restaurar_baja(bigint)'::regprocedure)) <> 'bccbb1da5ba97d91c44f6cc0976227c7' THEN
    RAISE EXCEPTION 'f_dar_baja o f_restaurar_baja no son las de la migración 002: revisa sus definiciones antes de aplicar la 012.';
  END IF;
END $$;

-- ---------------------------------------------------------------------
-- 1. Definiciones de los campos
-- ---------------------------------------------------------------------

CREATE TABLE public.campos_activo (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clave      text NOT NULL CONSTRAINT campos_activo_clave_formato CHECK (clave ~ '^[a-z][a-z0-9_]{0,39}$'),
  etiqueta   text NOT NULL CONSTRAINT campos_activo_etiqueta_valida CHECK (btrim(etiqueta) <> '' AND char_length(etiqueta) <= 60),
  tipo_dato  text NOT NULL CONSTRAINT campos_activo_tipo_dato_valido CHECK (tipo_dato IN ('texto', 'texto_largo', 'numero', 'fecha', 'si_no', 'lista')),
  unidad     text CONSTRAINT campos_activo_unidad_valida CHECK (unidad IS NULL OR (btrim(unidad) <> '' AND char_length(unidad) <= 12)),
  opciones   jsonb NOT NULL DEFAULT '[]'::jsonb CONSTRAINT campos_activo_opciones_lista CHECK (jsonb_typeof(opciones) = 'array'),
  fijo       boolean NOT NULL DEFAULT false,
  columna    text,
  unico      boolean NOT NULL DEFAULT false,
  en_acta    boolean NOT NULL DEFAULT false,
  orden      integer NOT NULL DEFAULT 0,
  activo     boolean NOT NULL DEFAULT true,
  creado_en  timestamptz NOT NULL DEFAULT now(),
  creado_por uuid DEFAULT auth.uid(),
  CONSTRAINT campos_activo_clave_unica UNIQUE (clave),
  CONSTRAINT campos_activo_columna_de_fijo CHECK ((fijo AND columna IS NOT NULL) OR (NOT fijo AND columna IS NULL)),
  CONSTRAINT campos_activo_unico_con_sentido CHECK (NOT unico OR tipo_dato IN ('texto', 'numero')),
  CONSTRAINT campos_activo_lista_con_opciones CHECK (tipo_dato <> 'lista' OR jsonb_array_length(opciones) > 0)
);
COMMENT ON TABLE public.campos_activo IS 'Campos de los activos (migración 012). fijo = uno de los 9 de siempre (columna de activos); los demás guardan su valor en activos.personalizados. clave fija; etiqueta, unidad, opciones, reglas y orden editables.';
COMMENT ON COLUMN public.campos_activo.opciones IS 'Solo para tipo_dato = lista: [{ "valor": texto fijo, "etiqueta": texto editable, "activo": bool }]. Una opción que ya usan activos no se quita: se desactiva.';
CREATE UNIQUE INDEX campos_activo_etiqueta_unica ON public.campos_activo (lower(btrim(etiqueta)));

INSERT INTO public.campos_activo (clave, etiqueta, tipo_dato, unidad, fijo, columna, orden) VALUES
  ('serie',        'Serie',             'texto',  NULL, true, 'serie',             10),
  ('so',           'Sistema operativo', 'texto',  NULL, true, 'sistema_operativo', 20),
  ('ram_gb',       'RAM',               'numero', 'GB', true, 'ram_gb',            30),
  ('disco_gb',     'Almacenamiento',    'numero', 'GB', true, 'disco_gb',          40),
  ('procesador',   'Procesador',        'texto',  NULL, true, 'procesador',        50),
  ('mac_wifi',     'MAC WiFi',          'texto',  NULL, true, 'mac_wifi',          60),
  ('mac_ethernet', 'MAC Ethernet',      'texto',  NULL, true, 'mac_ethernet',      70),
  ('color',        'Color',             'texto',  NULL, true, 'color',             80),
  ('longitud_m',   'Longitud',          'numero', 'm',  true, 'longitud_m',        90);

-- Valor normalizado para comparar «único»: sin mayúsculas ni espacios de
-- más; los números, como números (12, 12.0 y 12,00 son lo mismo).
CREATE FUNCTION public.f_valor_comparable(p_valor text, p_tipo text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = ''
AS $$
  SELECT CASE
    WHEN p_valor IS NULL OR btrim(p_valor) = '' THEN NULL
    WHEN p_tipo = 'numero' AND btrim(p_valor) ~ '^[-+]?([0-9]+[.]?[0-9]*|[.][0-9]+)([eE][-+]?[0-9]+)?$'
      THEN 'n:' || pg_catalog.trim_scale(btrim(p_valor)::numeric)::text
    ELSE 't:' || lower(regexp_replace(btrim(p_valor), '\s+', ' ', 'g'))
  END
$$;
COMMENT ON FUNCTION public.f_valor_comparable(text, text) IS 'Valor normalizado de un campo para la regla «único» (migración 012).';

-- Reglas de las definiciones: los fijos no se borran, no cambian de clave,
-- de tipo de dato ni se desactivan; las claves reservadas no se usan; las
-- listas traen opciones válidas; «único» no se marca con repetidos; y un
-- campo con valores no se borra ni cambia de tipo de dato.
CREATE FUNCTION public.f_campos_activo_validar()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_fijos constant jsonb := '{"serie":"serie","so":"sistema_operativo","ram_gb":"ram_gb","disco_gb":"disco_gb","procesador":"procesador","mac_wifi":"mac_wifi","mac_ethernet":"mac_ethernet","color":"color","longitud_m":"longitud_m"}';
  v_reservadas constant text[] := ARRAY['id','propiedad','tipo','marca','modelo','nombre_dispositivo','sistema_operativo','proveedor','fecha_adquisicion',
    'celular','celular_gmail','celular_password','gmail','password','trazabilidad','creado_en','valor_compra','vida_util_anios','fotos','estado',
    'personalizados','custodio','historial_custodia','historial_ubicacion','nombre','cargo','tag','acciones','ubicacion'];
  v_valores text[] := '{}';
  v_o jsonb;
  v_n integer;
  v_con_valores boolean;
BEGIN
  IF TG_OP = 'DELETE' THEN
    IF OLD.fijo THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = format('«%s» es un campo de siempre: no se borra.', OLD.etiqueta);
    END IF;
    IF EXISTS (SELECT 1 FROM public.activos a WHERE a.personalizados ? OLD.clave)
       OR EXISTS (SELECT 1 FROM public.bajas b WHERE b.activo -> 'personalizados' ? OLD.clave) THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = format('El campo «%s» tiene valores guardados: desactívalo en vez de borrarlo.', OLD.etiqueta);
    END IF;
    RETURN OLD;
  END IF;

  NEW.etiqueta := btrim(NEW.etiqueta);
  NEW.unidad := nullif(btrim(NEW.unidad), '');

  IF TG_OP = 'INSERT' THEN
    IF NEW.fijo THEN
      IF (v_fijos ->> NEW.clave) IS DISTINCT FROM NEW.columna THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'Solo los 9 campos de siempre son fijos.';
      END IF;
    ELSIF NEW.clave = ANY (v_reservadas) OR v_fijos ? NEW.clave THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = format('La clave «%s» está reservada: elige otra etiqueta.', NEW.clave);
    END IF;
  ELSE
    IF NEW.clave <> OLD.clave OR NEW.fijo <> OLD.fijo OR NEW.columna IS DISTINCT FROM OLD.columna THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'La clave de un campo no cambia.';
    END IF;
    IF OLD.fijo AND (NEW.tipo_dato <> OLD.tipo_dato OR NOT NEW.activo) THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = format('«%s» es un campo de siempre: no cambia de tipo de dato ni se desactiva.', OLD.etiqueta);
    END IF;
    IF NOT OLD.fijo AND NEW.tipo_dato <> OLD.tipo_dato THEN
      v_con_valores := EXISTS (SELECT 1 FROM public.activos a WHERE a.personalizados ? OLD.clave)
                    OR EXISTS (SELECT 1 FROM public.bajas b WHERE b.activo -> 'personalizados' ? OLD.clave);
      IF v_con_valores THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = format('No se puede cambiar el tipo de dato de «%s»: ya hay activos con un valor.', OLD.etiqueta);
      END IF;
    END IF;
  END IF;

  IF NEW.tipo_dato <> 'numero' THEN NEW.unidad := NULL; END IF;

  IF NEW.tipo_dato <> 'lista' THEN
    NEW.opciones := '[]'::jsonb;
  ELSE
    FOR v_o IN SELECT value FROM jsonb_array_elements(NEW.opciones) LOOP
      IF jsonb_typeof(v_o) <> 'object'
         OR coalesce(btrim(v_o ->> 'valor'), '') = '' OR coalesce(btrim(v_o ->> 'etiqueta'), '') = ''
         OR char_length(v_o ->> 'valor') > 60 OR char_length(v_o ->> 'etiqueta') > 60
         OR (v_o ? 'activo' AND jsonb_typeof(v_o -> 'activo') <> 'boolean') THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'Cada opción de la lista necesita un valor y un nombre (hasta 60 caracteres).';
      END IF;
      IF (v_o ->> 'valor') = ANY (v_valores) THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = format('La opción «%s» está repetida.', v_o ->> 'etiqueta');
      END IF;
      v_valores := v_valores || (v_o ->> 'valor');
    END LOOP;
    IF NOT EXISTS (SELECT 1 FROM jsonb_array_elements(NEW.opciones) x WHERE coalesce((x.value ->> 'activo')::boolean, true)) THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'Una lista necesita al menos una opción activa.';
    END IF;
    IF TG_OP = 'UPDATE' AND OLD.tipo_dato = 'lista' AND EXISTS (
         SELECT 1 FROM jsonb_array_elements(OLD.opciones) x
          WHERE NOT ((x.value ->> 'valor') = ANY (v_valores))
            AND EXISTS (SELECT 1 FROM public.activos a WHERE a.personalizados ->> OLD.clave = x.value ->> 'valor')) THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'Una opción que ya tienen activos no se quita: desactívala.';
    END IF;
  END IF;

  IF NEW.unico AND (TG_OP = 'INSERT' OR NOT OLD.unico) THEN
    IF NEW.fijo THEN
      EXECUTE format('SELECT count(*) FROM (SELECT public.f_valor_comparable(a.%1$I::text, $1) FROM public.activos a WHERE nullif(btrim(a.%1$I::text), '''') IS NOT NULL GROUP BY 1 HAVING count(*) > 1) x', NEW.columna)
        INTO v_n USING NEW.tipo_dato;
    ELSE
      SELECT count(*) INTO v_n FROM (
        SELECT public.f_valor_comparable(a.personalizados ->> NEW.clave, NEW.tipo_dato)
          FROM public.activos a
         WHERE nullif(btrim(a.personalizados ->> NEW.clave), '') IS NOT NULL
         GROUP BY 1 HAVING count(*) > 1) x;
    END IF;
    IF v_n > 0 THEN
      RAISE EXCEPTION USING ERRCODE = '23505', MESSAGE = format('No se puede marcar «%s» como único: hay %s valor%s repetido%s entre los activos.', NEW.etiqueta, v_n, CASE WHEN v_n = 1 THEN '' ELSE 'es' END, CASE WHEN v_n = 1 THEN '' ELSE 's' END);
    END IF;
  END IF;

  RETURN NEW;
END $$;

CREATE TRIGGER trg_campos_activo_validar BEFORE INSERT OR UPDATE OR DELETE ON public.campos_activo
  FOR EACH ROW EXECUTE FUNCTION public.f_campos_activo_validar();
CREATE TRIGGER audit_campos_activo AFTER INSERT OR DELETE OR UPDATE ON public.campos_activo
  FOR EACH ROW EXECUTE FUNCTION public.registrar_auditoria();

-- ---------------------------------------------------------------------
-- 2. Valores: activos.personalizados
-- ---------------------------------------------------------------------

ALTER TABLE public.activos
  ADD COLUMN personalizados jsonb NOT NULL DEFAULT '{}'::jsonb
    CONSTRAINT activos_personalizados_objeto CHECK (jsonb_typeof(personalizados) = 'object');
COMMENT ON COLUMN public.activos.personalizados IS 'Valores de los campos nuevos (campos_activo, no fijos): { clave: valor }. La base mezcla lo que llega con lo que había y quita los null (migración 012).';

-- Mezcla y valida (va antes que «único»: los triggers BEFORE corren por nombre).
-- Al restaurar una baja (f_restaurar_baja) no se validan los valores: son
-- los que el activo ya tenía.
CREATE FUNCTION public.f_activos_personalizados()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
DECLARE
  r record;
  c record;
  v_txt text;
  v_fecha date;
BEGIN
  IF TG_OP = 'UPDATE' THEN
    IF jsonb_typeof(coalesce(NEW.personalizados, '{}'::jsonb)) <> 'object' THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'personalizados tiene que ser un objeto { clave: valor }.';
    END IF;
    NEW.personalizados := jsonb_strip_nulls(coalesce(OLD.personalizados, '{}'::jsonb) || coalesce(NEW.personalizados, '{}'::jsonb));
  ELSE
    NEW.personalizados := jsonb_strip_nulls(coalesce(NEW.personalizados, '{}'::jsonb));
  END IF;
  IF jsonb_typeof(NEW.personalizados) <> 'object' THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'personalizados tiene que ser un objeto { clave: valor }.';
  END IF;
  IF coalesce(current_setting('lukmar.restaurando_baja', true), '') = 'si' THEN
    RETURN NEW;
  END IF;
  FOR r IN SELECT key, value FROM jsonb_each(NEW.personalizados) LOOP
    CONTINUE WHEN TG_OP = 'UPDATE' AND (OLD.personalizados -> r.key) IS NOT DISTINCT FROM r.value;
    SELECT ca.clave, ca.etiqueta, ca.tipo_dato, ca.opciones INTO c FROM public.campos_activo ca WHERE ca.clave = r.key AND NOT ca.fijo;
    IF NOT FOUND THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = format('El campo «%s» no existe (o es uno de siempre, que va en su columna).', r.key);
    END IF;
    v_txt := r.value #>> '{}';
    IF c.tipo_dato = 'numero' AND jsonb_typeof(r.value) <> 'number' THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = format('«%s» tiene que ser un número.', c.etiqueta);
    ELSIF c.tipo_dato = 'si_no' AND jsonb_typeof(r.value) <> 'boolean' THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = format('«%s» tiene que ser sí o no.', c.etiqueta);
    ELSIF c.tipo_dato IN ('texto', 'texto_largo', 'fecha', 'lista') AND jsonb_typeof(r.value) <> 'string' THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = format('«%s» tiene que ser un texto.', c.etiqueta);
    ELSIF c.tipo_dato = 'texto' AND char_length(v_txt) > 500 THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = format('«%s» admite hasta 500 caracteres.', c.etiqueta);
    ELSIF c.tipo_dato = 'texto_largo' AND char_length(v_txt) > 4000 THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = format('«%s» admite hasta 4000 caracteres.', c.etiqueta);
    ELSIF c.tipo_dato = 'fecha' THEN
      IF v_txt !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = format('«%s»: la fecha no es válida.', c.etiqueta);
      END IF;
      BEGIN
        v_fecha := v_txt::date;
      EXCEPTION WHEN others THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = format('«%s»: la fecha no es válida.', c.etiqueta);
      END;
    ELSIF c.tipo_dato = 'lista' AND NOT EXISTS (
        SELECT 1 FROM jsonb_array_elements(c.opciones) o
         WHERE o.value ->> 'valor' = v_txt AND coalesce((o.value ->> 'activo')::boolean, true)) THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = format('«%s»: «%s» no es una de sus opciones activas.', c.etiqueta, v_txt);
    END IF;
  END LOOP;
  RETURN NEW;
END $$;

-- «Único»: el valor no se repite entre activos (solo se revisa si cambió).
-- SECURITY DEFINER: tiene que ver todos los activos, sin depender de RLS.
CREATE FUNCTION public.f_activos_campos_unicos()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  c record;
  v_nuevo text;
  v_viejo text;
  v_otro integer;
  v_prop text;
BEGIN
  FOR c IN SELECT ca.clave, ca.etiqueta, ca.tipo_dato, ca.fijo, ca.columna FROM public.campos_activo ca WHERE ca.unico ORDER BY ca.orden, ca.clave LOOP
    IF c.fijo THEN
      EXECUTE format('SELECT ($1).%1$I::text', c.columna) INTO v_nuevo USING NEW;
      IF TG_OP = 'UPDATE' THEN EXECUTE format('SELECT ($1).%1$I::text', c.columna) INTO v_viejo USING OLD; ELSE v_viejo := NULL; END IF;
    ELSE
      v_nuevo := NEW.personalizados ->> c.clave;
      v_viejo := CASE WHEN TG_OP = 'UPDATE' THEN OLD.personalizados ->> c.clave END;
    END IF;
    CONTINUE WHEN public.f_valor_comparable(v_nuevo, c.tipo_dato) IS NULL;
    CONTINUE WHEN TG_OP = 'UPDATE' AND public.f_valor_comparable(v_nuevo, c.tipo_dato) IS NOT DISTINCT FROM public.f_valor_comparable(v_viejo, c.tipo_dato);
    -- Dos altas a la vez con el mismo valor: una espera a la otra.
    PERFORM pg_advisory_xact_lock(hashtext('activos_unico:' || c.clave));
    IF c.fijo THEN
      EXECUTE format('SELECT a.id FROM public.activos a WHERE a.id <> $1 AND public.f_valor_comparable(a.%1$I::text, $2) = public.f_valor_comparable($3, $2) ORDER BY a.id LIMIT 1', c.columna)
        INTO v_otro USING NEW.id, c.tipo_dato, v_nuevo;
    ELSE
      SELECT a.id INTO v_otro FROM public.activos a
       WHERE a.id <> NEW.id AND public.f_valor_comparable(a.personalizados ->> c.clave, c.tipo_dato) = public.f_valor_comparable(v_nuevo, c.tipo_dato)
       ORDER BY a.id LIMIT 1;
    END IF;
    IF v_otro IS NOT NULL THEN
      SELECT a.propiedad INTO v_prop FROM public.activos a WHERE a.id = v_otro;
      RAISE EXCEPTION USING ERRCODE = '23505',
        MESSAGE = format('Ya hay otro activo con el mismo «%s» (%s-%s).', c.etiqueta, CASE WHEN v_prop = 'eq' THEN 'EQS' ELSE 'LKM' END, CASE WHEN length(v_otro::text) < 3 THEN lpad(v_otro::text, 3, '0') ELSE v_otro::text END);
    END IF;
  END LOOP;
  RETURN NEW;
END $$;

CREATE TRIGGER trg_activos_a_personalizados BEFORE INSERT OR UPDATE ON public.activos
  FOR EACH ROW EXECUTE FUNCTION public.f_activos_personalizados();
CREATE TRIGGER trg_activos_b_campos_unicos BEFORE INSERT OR UPDATE ON public.activos
  FOR EACH ROW EXECUTE FUNCTION public.f_activos_campos_unicos();

-- ---------------------------------------------------------------------
-- 3. Tipos: campos obligatorios; íconos limpios desde ahora
-- ---------------------------------------------------------------------

ALTER TABLE public.tipos_activo
  ADD COLUMN campos_obligatorios jsonb NOT NULL DEFAULT '[]'::jsonb
    CONSTRAINT tipos_activo_obligatorios_lista CHECK (jsonb_typeof(campos_obligatorios) = 'array');
COMMENT ON COLUMN public.tipos_activo.campos_obligatorios IS 'Claves de campos_activo que el formulario del activo exige para este tipo (migración 012). Solo cuentan las que también están en campos_pertinentes.';

-- Los íconos se muestran a todos: no pueden traer scripts ni eventos (el
-- navegador lee un evento también pegado a una barra o a una comilla:
-- «<path/onload=…», «d="x"onload=…»). NOT VALID: rige para lo que se guarde
-- desde ahora (los de siempre no se tocan).
ALTER TABLE public.tipos_activo
  ADD CONSTRAINT tipos_activo_icono_seguro CHECK (
    icono_svg !~* '<\s*script' AND icono_svg !~* 'javascript\s*:' AND icono_svg !~* '[\s/"'']on[a-z]+\s*=' AND icono_svg !~* '<\s*foreignObject'
  ) NOT VALID;

ALTER TABLE public.tipos_ubicacion
  ADD COLUMN icono_svg text
    CONSTRAINT tipos_ubicacion_icono_valido CHECK (icono_svg IS NULL OR (
      char_length(icono_svg) <= 20000 AND icono_svg ~* '^\s*<svg[\s>]'
      AND icono_svg !~* '<\s*script' AND icono_svg !~* 'javascript\s*:' AND icono_svg !~* '[\s/"'']on[a-z]+\s*=' AND icono_svg !~* '<\s*foreignObject'));
COMMENT ON COLUMN public.tipos_ubicacion.icono_svg IS 'Ícono de la burbuja en el mapa (SVG con viewBox). NULL = el dibujo de fábrica (migración 012).';

-- ---------------------------------------------------------------------
-- 4. Cambiar el nombre de un tipo de activo
-- ---------------------------------------------------------------------

CREATE FUNCTION public.renombrar_tipo_activo(p_viejo text, p_nuevo text)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_nuevo text := btrim(p_nuevo);
  v_n integer;
BEGIN
  IF NOT public.es_admin() THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'Solo el administrador puede cambiar el nombre de un tipo.';
  END IF;
  IF p_viejo IS NULL OR NOT EXISTS (SELECT 1 FROM public.tipos_activo t WHERE t.nombre = p_viejo) THEN
    RAISE EXCEPTION USING ERRCODE = 'P0002', MESSAGE = format('El tipo «%s» no existe.', p_viejo);
  END IF;
  IF p_viejo = 'Celular' THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = '«Celular» no se puede renombrar: ese nombre activa los datos de celular.';
  END IF;
  IF v_nuevo IS NULL OR v_nuevo = '' OR char_length(v_nuevo) > 60 THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'El nombre nuevo no puede quedar vacío (hasta 60 caracteres).';
  END IF;
  IF v_nuevo = p_viejo THEN
    RETURN 0;
  END IF;
  IF EXISTS (SELECT 1 FROM public.tipos_activo t WHERE lower(btrim(t.nombre)) = lower(v_nuevo) AND t.nombre <> p_viejo) THEN
    RAISE EXCEPTION USING ERRCODE = '23505', MESSAGE = format('Ya existe un tipo que se llama «%s».', v_nuevo);
  END IF;
  SELECT count(*) INTO v_n FROM public.activos a WHERE a.tipo = p_viejo;
  -- activos_tipo_fkey (ON UPDATE CASCADE) lleva el nombre nuevo a activos.tipo.
  UPDATE public.tipos_activo SET nombre = v_nuevo WHERE nombre = p_viejo;
  UPDATE public.bajas SET activo = jsonb_set(activo, '{tipo}', to_jsonb(v_nuevo)) WHERE activo ->> 'tipo' = p_viejo;
  RETURN v_n;
END $$;
COMMENT ON FUNCTION public.renombrar_tipo_activo(text, text) IS 'Cambia el nombre de un tipo de activo: la FK lo lleva a los activos y la función a las copias de las bajas. Devuelve cuántos activos cambiaron (migración 012).';
REVOKE ALL ON FUNCTION public.renombrar_tipo_activo(text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.renombrar_tipo_activo(text, text) TO authenticated;

-- ---------------------------------------------------------------------
-- 5. Reglas (RLS) y GRANT de campos_activo (el SQL Editor no los aplica solo)
-- ---------------------------------------------------------------------

ALTER TABLE public.campos_activo ENABLE ROW LEVEL SECURITY;
CREATE POLICY sel_campos_activo ON public.campos_activo FOR SELECT USING (true);
CREATE POLICY ins_campos_activo ON public.campos_activo FOR INSERT WITH CHECK (public.es_admin());
CREATE POLICY upd_campos_activo ON public.campos_activo FOR UPDATE USING (public.es_admin()) WITH CHECK (public.es_admin());
CREATE POLICY del_campos_activo ON public.campos_activo FOR DELETE USING (public.es_admin());
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.campos_activo TO anon, authenticated;

-- ---------------------------------------------------------------------
-- 6. Baja / restauración: la copia lleva también personalizados.
--    MISMA firma que las de la 002 (CREATE OR REPLACE conserva dueño y
--    permisos, y no crea sobrecargas). Los cambios están marcados «012».
-- ---------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.f_dar_baja(p_activo_id integer, p_motivo text)
 RETURNS void
 LANGUAGE plpgsql
AS $function$ declare v_snapshot jsonb; begin select jsonb_build_object( 'id', a.id, 'propiedad', a.propiedad, 'tipo', a.tipo, 'marca', a.marca, 'modelo', a.modelo, 'serie', a.serie, 'nombre_dispositivo', a.nombre_dispositivo, 'mac_wifi', a.mac_wifi, 'mac_ethernet', a.mac_ethernet, 'sistema_operativo', a.sistema_operativo, 'ram_gb', a.ram_gb, 'disco_gb', a.disco_gb, 'procesador', a.procesador, 'proveedor', a.proveedor, 'fecha_adquisicion', a.fecha_adquisicion, 'celular_gmail', a.celular_gmail, 'celular_password', a.celular_password, 'trazabilidad', a.trazabilidad, 'estado', a.estado, 'valor_compra', a.valor_compra, 'vida_util_anios', a.vida_util_anios, 'color', a.color, 'longitud_m', a.longitud_m, 'fotos', a.fotos, 'historial_custodia', coalesce(( select jsonb_agg(jsonb_build_object('orden', h.orden, 'tipo_custodio', h.tipo_custodio, 'nombre', h.nombre, 'cargo', h.cargo, 'desde', h.desde, 'hasta', h.hasta, 'tipo_devolucion', h.tipo_devolucion, 'tipo_entrega', h.tipo_entrega, 'observacion_entrega', h.observacion_entrega, 'observacion_devolucion', h.observacion_devolucion) order by h.orden) from public.historial_custodia h where h.activo_id = a.id), '[]'::jsonb)
  -- «002» historial de ubicación en el snapshot (con el nombre, por si la ubicación se borra después)
  , 'historial_ubicacion', coalesce(( select jsonb_agg(jsonb_build_object('ubicacion_id', hu.ubicacion_id, 'ubicacion', u.nombre, 'desde', hu.desde, 'hasta', hu.hasta, 'notas', hu.notas, 'registrado_por', hu.registrado_por) order by hu.desde, hu.id) from public.historial_ubicacion hu left join public.ubicaciones u on u.id = hu.ubicacion_id where hu.activo_id = a.id), '[]'::jsonb)
  -- «012» valores de los campos nuevos
  , 'personalizados', coalesce(a.personalizados, '{}'::jsonb)
  ) into v_snapshot from public.activos a where a.id = p_activo_id; if v_snapshot is null then raise exception 'Activo % no encontrado', p_activo_id; end if; insert into public.bajas (activo, motivo, dado_de_baja_por) values (v_snapshot, p_motivo, auth.uid()); delete from public.activos where id = p_activo_id; end; $function$;

CREATE OR REPLACE FUNCTION public.f_restaurar_baja(p_baja_id bigint)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$ declare v_activo jsonb; v_nuevo_id integer; begin select activo into v_activo from public.bajas where id = p_baja_id; if v_activo is null then raise exception 'Baja % no encontrada', p_baja_id; end if;
  -- «012» los valores de los campos nuevos vuelven tal cual (no se revalidan)
  perform set_config('lukmar.restaurando_baja', 'si', true);
  insert into public.activos (propiedad, tipo, marca, modelo, serie, nombre_dispositivo, mac_wifi, mac_ethernet, sistema_operativo, ram_gb, disco_gb, procesador, proveedor, fecha_adquisicion, celular_gmail, celular_password, trazabilidad, estado, valor_compra, vida_util_anios, color, longitud_m, fotos, personalizados) values (case when v_activo->>'propiedad' = 'propio' then coalesce(v_activo->>'empresa', 'lukmar') else v_activo->>'propiedad' end, v_activo->>'tipo', v_activo->>'marca', v_activo->>'modelo', v_activo->>'serie', v_activo->>'nombre_dispositivo', v_activo->>'mac_wifi', v_activo->>'mac_ethernet', v_activo->>'sistema_operativo', (v_activo->>'ram_gb')::numeric, (v_activo->>'disco_gb')::numeric, v_activo->>'procesador', v_activo->>'proveedor', (v_activo->>'fecha_adquisicion')::date, v_activo->>'celular_gmail', v_activo->>'celular_password', coalesce(v_activo->'trazabilidad', 'null'::jsonb), coalesce(v_activo->>'estado', 'uso'), (v_activo->>'valor_compra')::numeric, (v_activo->>'vida_util_anios')::numeric, v_activo->>'color', (v_activo->>'longitud_m')::numeric, case when jsonb_typeof(v_activo->'fotos') = 'array' then (select array_agg(x) from jsonb_array_elements_text(v_activo->'fotos') x) else array[]::text[] end, case when jsonb_typeof(v_activo->'personalizados') = 'object' then v_activo->'personalizados' else '{}'::jsonb end ) returning id into v_nuevo_id;
  perform set_config('lukmar.restaurando_baja', '', true);
  insert into public.historial_custodia (activo_id, orden, tipo_custodio, nombre, cargo, desde, hasta, tipo_devolucion, tipo_entrega, observacion_entrega, observacion_devolucion) select v_nuevo_id, (t->>'orden')::int, t->>'tipo_custodio', t->>'nombre', t->>'cargo', (t->>'desde')::date, (t->>'hasta')::date, t->>'tipo_devolucion', t->>'tipo_entrega', t->>'observacion_entrega', coalesce(t->>'observacion_devolucion', t->>'observacion') from jsonb_array_elements(coalesce(v_activo->'historial_custodia', '[]'::jsonb)) as t;
  -- «002» reinsertar el historial de ubicación con el id nuevo (se omiten tramos de ubicaciones que ya no existen)
  insert into public.historial_ubicacion (activo_id, ubicacion_id, desde, hasta, notas, registrado_por) select v_nuevo_id, (t->>'ubicacion_id')::bigint, (t->>'desde')::date, (t->>'hasta')::date, t->>'notas', (t->>'registrado_por')::uuid from jsonb_array_elements(coalesce(v_activo->'historial_ubicacion', '[]'::jsonb)) as t where exists (select 1 from public.ubicaciones u where u.id = (t->>'ubicacion_id')::bigint);
  delete from public.bajas where id = p_baja_id; return v_nuevo_id; end; $function$;

COMMIT;
